dotenv: .env
wallets:
  owner: ${OWNER_PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - OpenZeppelin/openzeppelin-contracts@4.7.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
networks:
  development:
    vrf_key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
  rinkeby:
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    vrf_key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    vrf_subscription_id: ${CHAINLINK_VRF_SUBSCIPTION_ID}
  mainnet-fork:
    vrf_coordinator: "0x271682DEB8C4E0901D1a1550aD2e64D568E69909"
    vrf_key_hash: "0x8af398995b04c28e9951adb9721ef74c74f93e6a478f39e7e0777be13527e7ef"
ipfs_url: ${IPFS_URL}
pinata:
  api_key: ${PINATA_API_KEY}
  api_secret: ${PINATA_API_SECRET}
   